const periodicTable = [
  [
    { symbol: "H", atomicNo: 1 ,color: "#F1B092" },
     null,
     null,
     null,
     null,
     null, 
     null,
     null,
     null,
     null,
     null,
     null,
     null,
     null,
     null,
     null,
     null,
    { symbol: "He", atomicNo: 2 , color: "#EEEEEE"}
  ],

  [
    { symbol: "Li", atomicNo: 3 , color: "#FAE1B8" },
    { symbol: "Be", atomicNo: 4 , color: "#F6CD8B" },
     null,
     null,
     null,
     null, 
     null, 
     null, 
     null, 
     null, 
     null, 
     null, 
     { symbol: "B", atomicNo: 5 , color: "#FEF188" }, 
     { symbol: "C", atomicNo: 6 , color: "#F2AE96" }, 
     { symbol: "N", atomicNo: 7 , color: "#F2AE96" }, 
     { symbol: "O", atomicNo: 8 , color: "#F2AE96" }, 
     { symbol: "F", atomicNo: 9 , color: "#AFD5AA" }, 
     { symbol: "Ne", atomicNo: 10 , color: "#EEEEEE" }
    ],

  [
    { symbol: "Na", atomicNo: 11 , color: "#FAE1B8" }, 
    { symbol: "Mg", atomicNo: 12 , color: "#F6CD8B" }, 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    { symbol: "Al", atomicNo: 13 , color: "#F9CDD2" }, 
    { symbol: "Si", atomicNo: 14 , color: "#FEF188" }, 
    { symbol: "P", atomicNo: 15 , color: "#F2AE96" }, 
    { symbol: "S", atomicNo: 16 , color: "#F2AE96" }, 
    { symbol: "Cl", atomicNo: 17 , color: "#AFD5AA" }, 
    { symbol: "Ar", atomicNo: 18 , color: "#EEEEEE" }
  ],

  [
    { symbol: "K", atomicNo: 19 , color: "#FAE1B8" }, 
    { symbol: "Ca", atomicNo: 20 , color: "#F6CD8B" }, 
    { symbol: "Sc", atomicNo: 21 , color: "#E6EEA6" }, 
    { symbol: "Ti", atomicNo: 22 , color: "#CFC3E5" }, 
    { symbol: "V", atomicNo: 23 , color: "#CFC3E5" }, 
    { symbol: "Cr", atomicNo: 24 , color: "#CFC3E5" }, 
    { symbol: "Mn", atomicNo: 25 , color: "#CFC3E5" }, 
    { symbol: "Fe", atomicNo: 26 , color: "#CFC3E5" }, 
    { symbol: "Co", atomicNo: 27 , color: "#CFC3E5" }, 
    { symbol: "Ni", atomicNo: 28 , color: "#CFC3E5" }, 
    { symbol: "Cu", atomicNo: 29 , color: "#CFC3E5" }, 
    { symbol: "Zn", atomicNo: 30 , color: "#CFC3E5" }, 
    { symbol: "Ga", atomicNo: 31 , color: "#F9CDD2" }, 
    { symbol: "Ge", atomicNo: 32 , color: "#FEF188" }, 
    { symbol: "As", atomicNo: 33 , color: "#FEF188" }, 
    { symbol: "Se", atomicNo: 34 , color: "#F2AE96" }, 
    { symbol: "Br", atomicNo: 35 , color: "#AFD5AA" }, 
    { symbol: "Kr", atomicNo: 36 , color: "#EEEEEE" }
  ],
  [
    { symbol: "Rb", atomicNo: 37 , color: "#FAE1B8" }, 
    { symbol: "Sr", atomicNo: 38 , color: "#F6CD8B" }, 
    { symbol: "Y", atomicNo: 39  , color: "#E6EEA6"}, 
    { symbol: "Zr", atomicNo: 40 , color: "#CFC3E5" }, 
    { symbol: "Nb", atomicNo: 41 , color: "#CFC3E5" }, 
    { symbol: "Mo", atomicNo: 42 , color: "#CFC3E5" }, 
    { symbol: "Tc", atomicNo: 43 , color: "#CFC3E5" }, 
    { symbol: "Ru", atomicNo: 44 , color: "#CFC3E5" }, 
    { symbol: "Rh", atomicNo: 45 , color: "#CFC3E5" }, 
    { symbol: "Pd", atomicNo: 46 , color: "#CFC3E5" }, 
    { symbol: "Ag", atomicNo: 47 , color: "#CFC3E5" }, 
    { symbol: "Cd", atomicNo: 48 , color: "#CFC3E5" }, 
    { symbol: "In", atomicNo: 49 , color: "#F9CDD2" }, 
    { symbol: "Sn", atomicNo: 50 , color: "#F9CDD2" }, 
    { symbol: "Sb", atomicNo: 51 , color: "#FEF188" }, 
    { symbol: "Te", atomicNo: 52 , color: "#FEF188" }, 
    { symbol: "I", atomicNo: 53 , color: "#AFD5AA" }, 
    { symbol: "Xe", atomicNo: 54 , color: "#EEEEEE" }
  ],
  [
    { symbol: "Cs", atomicNo: 55 , color: "#FAE1B8" }, 
    { symbol: "Ba", atomicNo: 56 , color: "#F6CD8B" }, 
    { symbol: "La", atomicNo: 57 , color: "#E6EEA6" }, 
    { symbol: "Hf", atomicNo: 72 , color: "#CFC3E5" }, 
    { symbol: "Ta", atomicNo: 73 , color: "#CFC3E5" }, 
    { symbol: "W",  atomicNo: 74 , color: "#CFC3E5" }, 
    { symbol: "Re", atomicNo: 75 , color: "#CFC3E5" }, 
    { symbol: "Os", atomicNo: 76 , color: "#CFC3E5" }, 
    { symbol: "Ir", atomicNo: 77 , color: "#CFC3E5" }, 
    { symbol: "Pt", atomicNo: 78 , color: "#CFC3E5" }, 
    { symbol: "Au", atomicNo: 79 , color: "#CFC3E5" }, 
    { symbol: "Hg", atomicNo: 80 , color: "#CFC3E5" }, 
    { symbol: "Tl", atomicNo: 81 , color: "#F9CDD2" }, 
    { symbol: "Pb", atomicNo: 82 , color: "#F9CDD2" }, 
    { symbol: "Bi", atomicNo: 83 , color: "#FEF188" }, 
    { symbol: "Po", atomicNo: 84 , color: "#FEF188" }, 
    { symbol: "At", atomicNo: 85 , color: "#AFD5AA" }, 
    { symbol: "Rn", atomicNo: 86 , color: "#EEEEEE" }
  ],
  [
    { symbol: "Fr ", atomicNo: 87 , color: "#FAE1B8" }, 
    { symbol: "Ra", atomicNo: 88 , color: "#F6CD8B" }, 
    { symbol: "Ac", atomicNo: 89 , color: "#BDE4F9" }, 
    { symbol: "Rf", atomicNo: 104 , color: "#CFC3E5" }, 
    { symbol: "Db", atomicNo: 105 , color: "#CFC3E5" }, 
    { symbol: "Sg", atomicNo: 106 , color: "#CFC3E5" }, 
    { symbol: "Bh", atomicNo: 107 , color: "#CFC3E5" }, 
    { symbol: "Hs", atomicNo: 108 , color: "#CFC3E5" }, 
    { symbol: "Mt", atomicNo: 109 , color: "#CFC3E5" }, 
    { symbol: "Ds", atomicNo: 110 , color: "#CFC3E5" }, 
    { symbol: "Rg", atomicNo: 111 , color: "#CFC3E5" }, 
    { symbol: "Cn", atomicNo: 112 , color: "#CFC3E5" }, 
    { symbol: "Nh", atomicNo: 113 , color: "#F9CDD2" }, 
    { symbol: "Fl", atomicNo: 114 , color: "#F9CDD2" }, 
    { symbol: "Mc", atomicNo: 115 , color: "#F9CDD2" }, 
    { symbol: "Lv", atomicNo: 116 , color: "#F9CDD2" }, 
    { symbol: "Ts", atomicNo: 117 , color: "#AFD5AA" }, 
    { symbol: "Og", atomicNo: 118 , color: "#EEEEEE" }
  ]
];

const fBlockElements = [
  { symbol: "La", atomicNo: 57 , color: "#E6EEA6" },
  { symbol: "Ce", atomicNo: 58 , color: "#E6EEA6" },
  { symbol: "Pr", atomicNo: 59 , color: "#E6EEA6" },
  { symbol: "Nd", atomicNo: 60 , color: "#E6EEA6" },
  { symbol: "Pm", atomicNo: 61 , color: "#E6EEA6" },
  { symbol: "Sm", atomicNo: 62 , color: "#E6EEA6" },
  { symbol: "Eu", atomicNo: 63 , color: "#E6EEA6" },
  { symbol: "Gd", atomicNo: 64 , color: "#E6EEA6" },
  { symbol: "Tb", atomicNo: 65 , color: "#E6EEA6" },
  { symbol: "Dy", atomicNo: 66 , color: "#E6EEA6" },
  { symbol: "Ho", atomicNo: 67 , color: "#E6EEA6" },
  { symbol: "Er", atomicNo: 68 , color: "#E6EEA6" },
  { symbol: "Tm", atomicNo: 69 , color: "#E6EEA6" },
  { symbol: "Yb", atomicNo: 70 , color: "#E6EEA6" },
  { symbol: "Lu", atomicNo: 71 , color: "#E6EEA6" }
];

const actinideElements = [
  { symbol: "Ac", atomicNo: 89 , color: "#BDE4F9" },
  { symbol: "Th", atomicNo: 90 , color: "#BDE4F9" },
  { symbol: "Pa", atomicNo: 91 , color: "#BDE4F9" },
  { symbol: "U",  atomicNo: 92 , color: "#BDE4F9" },
  { symbol: "Np", atomicNo: 93 , color: "#BDE4F9" },
  { symbol: "Pu", atomicNo: 94 , color: "#BDE4F9" },
  { symbol: "Am", atomicNo: 95 , color: "#BDE4F9" },
  { symbol: "Cm", atomicNo: 96 , color: "#BDE4F9" },
  { symbol: "Bk", atomicNo: 97, color: "#BDE4F9" },
  { symbol: "Cf", atomicNo: 98 , color: "#BDE4F9" },
  { symbol: "Es", atomicNo: 99 , color: "#BDE4F9" },
  { symbol: "Fm", atomicNo: 100 , color: "#BDE4F9" },
  { symbol: "Md", atomicNo: 101 , color: "#BDE4F9" },
  { symbol: "No", atomicNo: 102 , color: "#BDE4F9" },
  { symbol: "Lr", atomicNo: 103 , color: "#BDE4F9" },
];

const fBlock = [
  { label: "Lanthanides", elements: fBlockElements },
  { label: "Actinides", elements: actinideElements }
];