const periodicTable = [
  [
    { symbol: "H", atomicNo: 1, color: "#F1B092", atomicMass: 1.008, name: "Hydrogen" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/f_auto,g_auto/v1735214156/s13_vsothx.jpg" ,state:"gas",metallicCharacter:"non-metal"},
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    { symbol: "He", atomicNo: 2, color: "#EEEEEE", atomicMass: 4.002602, name: "Helium",image:"https://res.cloudinary.com/ddgqnimxd/image/upload/f_auto,g_auto/v1735213997/helium_bivlyo.jpg" ,state:"gas",metallicCharacter:"non-metal"}
  ],

  [
    { symbol: "Li", atomicNo: 3, color: "#FAE1B8", atomicMass: 6.94, name: "Lithium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735214198/s13_dclr9g.jpg",state:"solid",metallicCharacter:"metal"},
    { symbol: "Be", atomicNo: 4, color: "#F6CD8B", atomicMass: 9.0122, name: "Beryllium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735238884/s13_es1toi.jpg",state:"solid",metallicCharacter:"metal"},
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    { symbol: "B", atomicNo: 5, color: "#FEF188", atomicMass: 10.81, name: "Boron" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735238929/s13_qehrap.jpg",state:"solid",metallicCharacter:"metalloid"},
    { symbol: "C", atomicNo: 6, color: "#F2AE96", atomicMass: 12.011, name: "Carbon" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735239027/s13_uz6hbw.jpg" ,state:"solid",metallicCharacter:"non-metal"},
    { symbol: "N", atomicNo: 7, color: "#F2AE96", atomicMass: 14.007, name: "Nitrogen" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735239420/s13_uvvgtg.jpg",state:"gas",metallicCharacter:"non-metal"},
    { symbol: "O", atomicNo: 8, color: "#F2AE96", atomicMass: 15.999, name: "Oxygen" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735239501/s13_oex3qu.jpg",state:"gas",metallicCharacter:"non-metal"},
    { symbol: "F", atomicNo: 9, color: "#AFD5AA", atomicMass: 18.998, name: "Fluorine" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735239625/s13_apxyor.jpg",state:"gas",metallicCharacter:"non-metal"},
    { symbol: "Ne", atomicNo: 10, color: "#EEEEEE", atomicMass: 20.180, name: "Neon" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735239652/s13_lpa292.jpg",state:"gas",metallicCharacter:"non-metal"}
  ],

  [
    { symbol: "Na", atomicNo: 11, color: "#FAE1B8", atomicMass: 22.990, name: "Sodium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735239676/s13_dmeeld.jpg",state:"solid",metallicCharacter:"metal"},
    { symbol: "Mg", atomicNo: 12, color: "#F6CD8B", atomicMass: 24.305, name: "Magnesium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735239900/s13_pealdx.jpg",state:"solid",metallicCharacter:"metal"},
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    { symbol: "Al", atomicNo: 13, color: "#F9CDD2", atomicMass: 26.982, name: "Aluminum" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735240882/s13_taau55.jpg",state:"solid",metallicCharacter:"metal"},
    { symbol: "Si", atomicNo: 14, color: "#FEF188", atomicMass: 28.085, name: "Silicon" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735240905/s13_c8pu2d.jpg",state:"solid",metallicCharacter:"metalloid"},
    { symbol: "P", atomicNo: 15, color: "#F2AE96", atomicMass: 30.974, name: "Phosphorus",image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735240926/s13_fwgyzc.jpg" ,state:"solid",metallicCharacter:"non-metal"},
    { symbol: "S", atomicNo: 16, color: "#F2AE96", atomicMass: 32.06, name: "Sulfur" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735240944/s13_gzwao2.jpg" ,state:"solid",metallicCharacter:"non-metal"},
    { symbol: "Cl", atomicNo: 17, color: "#AFD5AA", atomicMass: 35.45, name: "Chlorine" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735241196/s13_cu3ma4.jpg",state:"gas",metallicCharacter:"non-metal"},
    { symbol: "Ar", atomicNo: 18, color: "#EEEEEE", atomicMass: 39.948, name: "Argon" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735241212/s13_ewbemz.jpg",state:"gas",metallicCharacter:"non-metal"}
  ],

  [
    { symbol: "K", atomicNo: 19, color: "#FAE1B8", atomicMass: 39.098, name: "Potassium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735297263/s13_wxrjz9.jpg", state:"solid",metallicCharacter:"metal"},
    { symbol: "Ca", atomicNo: 20, color: "#F6CD8B", atomicMass: 40.078, name: "Calcium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735297293/s13_ccy8eb.jpg", state:"solid",metallicCharacter:"metal"},
    { symbol: "Sc", atomicNo: 21, color: "#E6EEA6", atomicMass: 44.956, name: "Scandium" ,image:"https://periodictable.com/Samples/021.8/s13.JPG", state:"solid",metallicCharacter:"metal"},
    { symbol: "Ti", atomicNo: 22, color: "#CFC3E5", atomicMass: 47.867, name: "Titanium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735298552/s13_z0vjy3.jpg", state:"solid",metallicCharacter:"metal"},
    { symbol: "V", atomicNo: 23, color: "#CFC3E5", atomicMass: 50.942, name: "Vanadium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735298684/s13_vgvy3m.jpg", state:"solid",metallicCharacter:"metal"},
    { symbol: "Cr", atomicNo: 24, color: "#CFC3E5", atomicMass: 51.996, name: "Chromium" ,image:"https://periodictable.com/Samples/024.11/s13.JPG", state:"solid",metallicCharacter:"metal"},
    { symbol: "Mn", atomicNo: 25, color: "#CFC3E5", atomicMass: 54.938, name: "Manganese" ,image:"https://periodictable.com/Samples/025.7/s13.JPG", state:"solid",metallicCharacter:"metal"},
    { symbol: "Fe", atomicNo: 26, color: "#CFC3E5", atomicMass: 55.845, name: "Iron" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735299047/s13_tk8vit.jpg", state:"solid",metallicCharacter:"metal"},
    { symbol: "Co", atomicNo: 27, color: "#CFC3E5", atomicMass: 58.933, name: "Cobalt" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735299240/s13_bxgllw.jpg", state:"solid",metallicCharacter:"metal"},
    { symbol: "Ni", atomicNo: 28, color: "#CFC3E5", atomicMass: 58.693, name: "Nickel" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735299306/s13_eoegqg.jpg", state:"solid",metallicCharacter:"metal"},
    { symbol: "Cu", atomicNo: 29, color: "#CFC3E5", atomicMass: 63.546, name: "Copper" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735299194/s13_ls8nni.jpg", state:"solid",metallicCharacter:"metal"},
    { symbol: "Zn", atomicNo: 30, color: "#CFC3E5", atomicMass: 65.38, name: "Zinc" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735299364/s13_nm3x5f.jpg", state:"solid",metallicCharacter:"metal"},
    { symbol: "Ga", atomicNo: 31, color: "#F9CDD2", atomicMass: 69.723, name: "Gallium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735321346/s13_f0h3qw.jpg", state:"solid",metallicCharacter:"metal"},
    { symbol: "Ge", atomicNo: 32, color: "#FEF188", atomicMass: 72.63, name: "Germanium" ,image:"https://periodictable.com/Samples/032.10/s13.JPG", state:"solid",metallicCharacter:"metalloid"},
    { symbol: "As", atomicNo: 33, color: "#FEF188", atomicMass: 74.922, name: "Arsenic" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735321468/s13_madwtw.jpg", state:"solid",metallicCharacter:"metalloid"},
    { symbol: "Se", atomicNo: 34, color: "#F2AE96", atomicMass: 78.971, name: "Selenium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735321499/s13_mcwgjo.jpg"  , state:"solid",metallicCharacter:"non-metal"},
    { symbol: "Br", atomicNo: 35, color: "#AFD5AA", atomicMass: 79.904, name: "Bromine" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735321755/s13_fatisr.jpg" , state:"liquid",metallicCharacter:"non-metal"},
    { symbol: "Kr", atomicNo: 36, color: "#EEEEEE", atomicMass: 83.798, name: "Krypton" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735321665/s13_ypun4n.jpg" , state:"gas",metallicCharacter:"non-metal"}
  ],
  [
    { symbol: "Rb", atomicNo: 37, color: "#FAE1B8", atomicMass: 85.468, name: "Rubidium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735321831/s13_kxekr7.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Sr", atomicNo: 38, color: "#F6CD8B", atomicMass: 87.62, name: "Strontium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735321937/s13_zasgjc.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Y", atomicNo: 39, color: "#E6EEA6", atomicMass: 88.906, name: "Yttrium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735321987/s13_i79rmd.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Zr", atomicNo: 40, color: "#CFC3E5", atomicMass: 91.224, name: "Zirconium",image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735321885/s13_ii2ijw.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Nb", atomicNo: 41, color: "#CFC3E5", atomicMass: 92.906, name: "Niobium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735322151/s13_flohnz.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Mo", atomicNo: 42, color: "#CFC3E5", atomicMass: 95.95, name: "Molybdenum" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735322395/s13_lwrgo0.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Tc", atomicNo: 43, color: "#CFC3E5", atomicMass: 98, name: "Technetium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735322368/s13_h1oj3m.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Ru", atomicNo: 44, color: "#CFC3E5", atomicMass: 101.07, name: "Ruthenium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735322494/s13_baywrx.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Rh", atomicNo: 45, color: "#CFC3E5", atomicMass: 102.91, name: "Rhodium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735322536/s13_hrtlcn.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Pd", atomicNo: 46, color: "#CFC3E5", atomicMass: 106.42, name: "Palladium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735322645/s13_sjkfys.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Ag", atomicNo: 47, color: "#CFC3E5", atomicMass: 107.87, name: "Silver" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735322753/s13_gybcmz.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Cd", atomicNo: 48, color: "#CFC3E5", atomicMass: 112.41, name: "Cadmium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735322832/s13_hywnrs.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "In", atomicNo: 49, color: "#F9CDD2", atomicMass: 114.82, name: "Indium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735323060/s13_szwutx.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Sn", atomicNo: 50, color: "#F9CDD2", atomicMass: 118.71, name: "Tin" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735323731/s13_mq0qjl.jpg" , state:"solid",metallicCharacter:"metalloid"},
    { symbol: "Sb", atomicNo: 51, color: "#FEF188", atomicMass: 121.76, name: "Antimony" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735323762/s13_ssc9s9.jpg" , state:"solid",metallicCharacter:"metalloid"},
    { symbol: "Te", atomicNo: 52, color: "#FEF188", atomicMass: 127.6, name: "Tellurium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735323814/s13_xze8oz.jpg" , state:"solid",metallicCharacter:"metalloid"},
    { symbol: "I", atomicNo: 53, color: "#AFD5AA", atomicMass: 126.9, name: "Iodine" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735323896/s13_aewjez.jpg" , state:"solid",metallicCharacter:"non-metal"},
    { symbol: "Xe", atomicNo: 54, color: "#EEEEEE", atomicMass: 131.29, name: "Xenon" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735323933/s13_apei9k.jpg" , state:"gas",metallicCharacter:"non-metal"}
  ],
  [
    { symbol: "Cs", atomicNo: 55, color: "#FAE1B8", atomicMass: 132.91, name: "Caesium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735323981/s13_foevyn.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Ba", atomicNo: 56, color: "#F6CD8B", atomicMass: 137.33, name: "Barium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735324012/s13_rjouab.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "La", atomicNo: 57, color: "#E6EEA6", atomicMass: 138.91, name: "Lanthanum" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735324046/s13_mb4wiq.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Hf", atomicNo: 72, color: "#CFC3E5", atomicMass: 178.49, name: "Hafnium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735324140/s13_ks38fe.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Ta", atomicNo: 73, color: "#CFC3E5", atomicMass: 180.95, name: "Tantalum" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735324275/s13_hqbo2d.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "W", atomicNo: 74, color: "#CFC3E5", atomicMass: 183.84, name: "Tungsten" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735324323/s13_lxnzet.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Re", atomicNo: 75, color: "#CFC3E5", atomicMass: 186.21, name: "Rhenium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735324407/s13_raac9d.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Os", atomicNo: 76, color: "#CFC3E5", atomicMass: 190.23, name: "Osmium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325119/s13_zags3z.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Ir", atomicNo: 77, color: "#CFC3E5", atomicMass: 192.22, name: "Iridium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325145/s13_tqcrzs.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Pt", atomicNo: 78, color: "#CFC3E5", atomicMass: 195.08, name: "Platinum" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325176/s13_uumwia.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Au", atomicNo: 79, color: "#CFC3E5", atomicMass: 196.97, name: "Gold" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325204/s13_ebzw97.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Hg", atomicNo: 80, color: "#CFC3E5", atomicMass: 200.59, name: "Mercury" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325314/s13_er0mxu.jpg" , state:"liquid",metallicCharacter:"metal"},
    { symbol: "Tl", atomicNo: 81, color: "#F9CDD2", atomicMass: 204.38, name: "Thallium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325564/s13_yepaib.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Pb", atomicNo: 82, color: "#F9CDD2", atomicMass: 207.2, name: "Lead" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325594/s13_rtstwh.jpg" , state:"solid",metallicCharacter:"metalloid"},
    { symbol: "Bi", atomicNo: 83, color: "#FEF188", atomicMass: 208.98, name: "Bismuth" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325622/s13_ydw5kp.jpg" , state:"solid",metallicCharacter:"metalloid"},
    { symbol: "Po", atomicNo: 84, color: "#FEF188", atomicMass: 209, name: "Polonium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325654/s13_puefwo.jpg" , state:"solid",metallicCharacter:"metalloid"},
    { symbol: "At", atomicNo: 85, color: "#AFD5AA", atomicMass: 210, name: "Astatine" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325691/s13_tmobne.jpg" , state:"solid",metallicCharacter:"non-metal"},
    { symbol: "Rn", atomicNo: 86, color: "#EEEEEE", atomicMass: 222, name: "Radon" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325722/s13_u42rkn.jpg" , state:"gas",metallicCharacter:"non-metal"}
  ],
  [
    { symbol: "Fr ", atomicNo: 87, color: "#FAE1B8", atomicMass: 223, name: "Francium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325858/s13_kdehie.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Ra", atomicNo: 88, color: "#F6CD8B", atomicMass: 226, name: "Radium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735325936/s13_k7ipdq.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Ac", atomicNo: 89, color: "#BDE4F9", atomicMass: 227, name: "Actinium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735366207/s13_g2obts.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Rf", atomicNo: 104, color: "#CFC3E5", atomicMass: 261, name: "Rutherfordium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735366325/s13_yldacw.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Db", atomicNo: 105, color: "#CFC3E5", atomicMass: 262, name: "Dubnium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735366364/s13_khnylz.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Sg", atomicNo: 106, color: "#CFC3E5", atomicMass: 266, name: "Seaborgium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735366395/s13_hk9htm.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Bh", atomicNo: 107, color: "#CFC3E5", atomicMass: 264, name: "Bohrium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735366895/s13_s0qzhg.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Hs", atomicNo: 108, color: "#CFC3E5", atomicMass: 269, name: "Hassium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735366918/s13_t0aiwl.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Mt", atomicNo: 109, color: "#CFC3E5", atomicMass: 268, name: "Meitnerium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735366941/s13_ozd89i.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Ds", atomicNo: 110, color: "#CFC3E5", atomicMass: 271, name: "Darmstadtium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735366965/s13_w9lwef.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Rg", atomicNo: 111, color: "#CFC3E5", atomicMass: 272, name: "Roentgenium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367003/s13_rpidet.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Cn", atomicNo: 112, color: "#CFC3E5", atomicMass: 285, name: "Copernicium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367033/s13_gv9emi.jpg" , state:"solid",metallicCharacter:"metal"},
    { symbol: "Nh", atomicNo: 113, color: "#F9CDD2", atomicMass: 286, name: "Nihonium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367079/s13_ensuqm.jpg" , state:"solid",metallicCharacter:"metalloid"},
    { symbol: "Fl", atomicNo: 114, color: "#F9CDD2", atomicMass: 289, name: "Flerovium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367106/s13_rhqhym.jpg" , state:"solid",metallicCharacter:"metalloid"},
    { symbol: "Mc", atomicNo: 115, color: "#F9CDD2", atomicMass: 288, name: "Moscovium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367137/s13_mngrr1.jpg" , state:"solid",metallicCharacter:"metalloid"},
    { symbol: "Lv", atomicNo: 116, color: "#F9CDD2", atomicMass: 293, name: "Livermorium" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367165/s13_zcsu2d.jpg" , state:"solid",metallicCharacter:"metalloid"},
    { symbol: "Ts", atomicNo: 117, color: "#AFD5AA", atomicMass: 294, name: "Tennessine" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367190/s13_xemild.jpg" , state:"solid",metallicCharacter:"non-metal"},
    { symbol: "Og", atomicNo: 118, color: "#EEEEEE", atomicMass: 294, name: "Oganesson" , image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367215/s13_mbzkuy.jpg" , state:"solid",metallicCharacter:"non-metal"}
  ]
];

const fBlockElements = [
{ symbol: "La", atomicNo: 57, color: "#E6EEA6", atomicMass: 138.90547, name: "Lanthanum" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735324046/s13_mb4wiq.jpg" , state:"solid",metallicCharacter:"metal"},

{ symbol: "Ce", atomicNo: 58, color: "#E6EEA6", atomicMass: 140.116, name: "Cerium",image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367354/s13_rpqone.jpg" , state:"solid",metallicCharacter:"metal"},
{ symbol: "Pr", atomicNo: 59, color: "#E6EEA6", atomicMass: 140.90765, name: "Praseodymium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367385/s13_bvuijl.jpg" , state:"solid",metallicCharacter:"metal"},
{ symbol: "Nd", atomicNo: 60, color: "#E6EEA6", atomicMass: 144.24, name: "Neodymium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367493/s13_tqtwum.jpg" , state:"solid",metallicCharacter:"metal"},
{ symbol: "Pm", atomicNo: 61, color: "#E6EEA6", atomicMass: 146.9151, name: "Promethium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367518/s13_klk7ot.jpg"  , state:"solid",metallicCharacter:"metal"},
{ symbol: "Sm", atomicNo: 62, color: "#E6EEA6", atomicMass: 150.36, name: "Samarium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367541/s13_hxenbo.jpg"  , state:"solid",metallicCharacter:"metal"},
{ symbol: "Eu", atomicNo: 63, color: "#E6EEA6", atomicMass: 151.964, name: "Europium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367564/s13_tze8yj.jpg"  , state:"solid",metallicCharacter:"metal"},
{ symbol: "Gd", atomicNo: 64, color: "#E6EEA6", atomicMass: 157.25, name: "Gadolinium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367587/s13_ueniwh.jpg"  , state:"solid",metallicCharacter:"metal"},
{ symbol: "Tb", atomicNo: 65, color: "#E6EEA6", atomicMass: 158.92535, name: "Terbium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367609/s13_xhat7m.jpg"  , state:"solid",metallicCharacter:"metal"},
{ symbol: "Dy", atomicNo: 66, color: "#E6EEA6", atomicMass: 162.5, name: "Dysprosium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367634/s13_le7pau.jpg"  , state:"solid",metallicCharacter:"metal"},
{ symbol: "Ho", atomicNo: 67, color: "#E6EEA6", atomicMass: 164.93032, name: "Holmium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367718/s13_momnnv.jpg"  , state:"solid",metallicCharacter:"metal"},
{ symbol: "Er", atomicNo: 68, color: "#E6EEA6", atomicMass: 167.259, name: "Erbium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367746/s13_rck0te.jpg"  , state:"solid",metallicCharacter:"metal"},
{ symbol: "Tm", atomicNo: 69, color: "#E6EEA6", atomicMass: 168.93422, name: "Thulium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367768/s13_w1yfry.jpg"  , state:"solid",metallicCharacter:"metal"},
{ symbol: "Yb", atomicNo: 70, color: "#E6EEA6", atomicMass: 173.04, name: "Ytterbium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367802/s13_phngqo.jpg"  , state:"solid",metallicCharacter:"metal"},
{ symbol: "Lu", atomicNo: 71, color: "#E6EEA6", atomicMass: 174.967, name: "Lutetium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367836/s13_ndoylz.jpg"  , state:"solid",metallicCharacter:"metal"},
];

const actinideElements = [
  { symbol: "Ac", atomicNo: 89, color: "#BDE4F9", atomicMass: 227, name: "Actinium" ,image:"https://res.cloudinary.com/ddgqnimxd/image/upload/v1735366207/s13_g2obts.jpg" , state:"solid",metallicCharacter:"metal"},
  { symbol: "Th", atomicNo: 90, color: "#BDE4F9", atomicMass: 232, name: "Thorium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367924/s13_zwk9ow.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Pa", atomicNo: 91, color: "#BDE4F9", atomicMass: 231, name: "Protactinium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367951/s13_vxrfvo.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "U", atomicNo: 92, color: "#BDE4F9", atomicMass: 238, name: "Uranium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735367980/s13_b6agjp.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Np", atomicNo: 93, color: "#BDE4F9", atomicMass: 237, name: "Neptunium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735368852/s13_niolqe.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Pu", atomicNo: 94, color: "#BDE4F9", atomicMass: 244, name: "Plutonium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735368878/s13_bdu2v1.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Am", atomicNo: 95, color: "#BDE4F9", atomicMass: 243, name: "Americium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735368911/s13_kelbye.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Cm", atomicNo: 96, color: "#BDE4F9", atomicMass: 247, name: "Curium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735368964/s13_xgfrsb.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Bk", atomicNo: 97, color: "#BDE4F9", atomicMass: 247, name: "Berkelium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735368990/s13_hxk3oq.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Cf", atomicNo: 98, color: "#BDE4F9", atomicMass: 251, name: "Californium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735369023/s13_dfldai.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Es", atomicNo: 99, color: "#BDE4F9", atomicMass: 252, name: "Einsteinium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735369059/s13_w0tj75.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Fm", atomicNo: 100, color: "#BDE4F9", atomicMass: 257, name: "Fermium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735369086/s13_c4amed.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Md", atomicNo: 101, color: "#BDE4F9", atomicMass: 258, name: "Mendelevium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735369110/s13_uw7hkk.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "No", atomicNo: 102, color: "#BDE4F9", atomicMass: 259, name: "Nobelium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735369133/s13_adfdmt.jpg"  , state:"solid",metallicCharacter:"metal"},
  { symbol: "Lr", atomicNo: 103, color: "#BDE4F9", atomicMass: 262, name: "Lawrencium", image: "https://res.cloudinary.com/ddgqnimxd/image/upload/v1735369147/s13_a4u9lq.jpg"  , state:"solid",metallicCharacter:"metal"},
];

const fBlock = [
  { label: "Lanthanides", elements: fBlockElements },
  { label: "Actinides", elements: actinideElements }
];