const periodicTable = [
  [
    { symbol: "H", atomicNo: 1, color: "#F1B092", atomicMass: 1.008, name: "Hydrogen" },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    { symbol: "He", atomicNo: 2, color: "#EEEEEE", atomicMass: 4.002602, name: "Helium" }
  ],

  [
    { symbol: "Li", atomicNo: 3, color: "#FAE1B8", atomicMass: 6.94, name: "Lithium" },
    { symbol: "Be", atomicNo: 4, color: "#F6CD8B", atomicMass: 9.0122, Name: "Beryllium" },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    { symbol: "B", atomicNo: 5, color: "#FEF188", atomicMass: 10.81, name: "Boron" },
    { symbol: "C", atomicNo: 6, color: "#F2AE96", atomicMass: 12.011, name: "Carbon" },
    { symbol: "N", atomicNo: 7, color: "#F2AE96", atomicMass: 14.007, name: "Nitrogen" },
    { symbol: "O", atomicNo: 8, color: "#F2AE96", atomicMass: 15.999, name: "Oxygen" },
    { symbol: "F", atomicNo: 9, color: "#AFD5AA", atomicMass: 18.998, name: "Fluorine" },
    { symbol: "Ne", atomicNo: 10, color: "#EEEEEE", atomicMass: 20.180, name: "Neon" }
  ],

  [
    { symbol: "Na", atomicNo: 11, color: "#FAE1B8", atomicMass: 22.990, name: "Sodium" },
    { symbol: "Mg", atomicNo: 12, color: "#F6CD8B", atomicMass: 24.305, name: "Magnesium" },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    { symbol: "Al", atomicNo: 13, color: "#F9CDD2", atomicMass: 26.982, name: "Aluminum" },
    { symbol: "Si", atomicNo: 14, color: "#FEF188", atomicMass: 28.085, name: "Silicon" },
    { symbol: "P", atomicNo: 15, color: "#F2AE96", atomicMass: 30.974, name: "Phosphorus" },
    { symbol: "S", atomicNo: 16, color: "#F2AE96", atomicMass: 32.06, name: "Sulfur" },
    { symbol: "Cl", atomicNo: 17, color: "#AFD5AA", atomicMass: 35.45, name: "Chlorine" },
    { symbol: "Ar", atomicNo: 18, color: "#EEEEEE", atomicMass: 39.948, name: "Argon" }
  ],

  [
    { symbol: "K", atomicNo: 19, color: "#FAE1B8", atomicMass: 39.098, name: "Potassium" },
    { symbol: "Ca", atomicNo: 20, color: "#F6CD8B", atomicMass: 40.078, name: "Calcium" },
    { symbol: "Sc", atomicNo: 21, color: "#E6EEA6", atomicMass: 44.956, name: "Scandium" },
    { symbol: "Ti", atomicNo: 22, color: "#CFC3E5", atomicMass: 47.867, name: "Titanium" },
    { symbol: "V", atomicNo: 23, color: "#CFC3E5", atomicMass: 50.942, name: "Vanadium" },
    { symbol: "Cr", atomicNo: 24, color: "#CFC3E5", atomicMass: 51.996, name: "Chromium" },
    { symbol: "Mn", atomicNo: 25, color: "#CFC3E5", atomicMass: 54.938, name: "Manganese" },
    { symbol: "Fe", atomicNo: 26, color: "#CFC3E5", atomicMass: 55.845, name: "Iron" },
    { symbol: "Co", atomicNo: 27, color: "#CFC3E5", atomicMass: 58.933, name: "Cobalt" },
    { symbol: "Ni", atomicNo: 28, color: "#CFC3E5", atomicMass: 58.693, name: "Nickel" },
    { symbol: "Cu", atomicNo: 29, color: "#CFC3E5", atomicMass: 63.546, name: "Copper" },
    { symbol: "Zn", atomicNo: 30, color: "#CFC3E5", atomicMass: 65.38, name: "Zinc" },
    { symbol: "Ga", atomicNo: 31, color: "#F9CDD2", atomicMass: 69.723, name: "Gallium" },
    { symbol: "Ge", atomicNo: 32, color: "#FEF188", atomicMass: 72.63, name: "Germanium" },
    { symbol: "As", atomicNo: 33, color: "#FEF188", atomicMass: 74.922, name: "Arsenic" },
    { symbol: "Se", atomicNo: 34, color: "#F2AE96", atomicMass: 78.971, name: "Selenium" },
    { symbol: "Br", atomicNo: 35, color: "#AFD5AA", atomicMass: 79.904, name: "Bromine" },
    { symbol: "Kr", atomicNo: 36, color: "#EEEEEE", atomicMass: 83.798, name: "Krypton" }
  ],
  [
    { symbol: "Rb", atomicNo: 37, color: "#FAE1B8", atomicMass: 85.468, name: "Rubidium" },
    { symbol: "Sr", atomicNo: 38, color: "#F6CD8B", atomicMass: 87.62, name: "Strontium" },
    { symbol: "Y", atomicNo: 39, color: "#E6EEA6", atomicMass: 88.906, name: "Yttrium" },
    { symbol: "Zr", atomicNo: 40, color: "#CFC3E5", atomicMass: 91.224, name: "Zirconium" },
    { symbol: "Nb", atomicNo: 41, color: "#CFC3E5", atomicMass: 92.906, name: "Niobium" },
    { symbol: "Mo", atomicNo: 42, color: "#CFC3E5", atomicMass: 95.95, name: "Molybdenum" },
    { symbol: "Tc", atomicNo: 43, color: "#CFC3E5", atomicMass: 98, name: "Technetium" },
    { symbol: "Ru", atomicNo: 44, color: "#CFC3E5", atomicMass: 101.07, name: "Ruthenium" },
    { symbol: "Rh", atomicNo: 45, color: "#CFC3E5", atomicMass: 102.91, name: "Rhodium" },
    { symbol: "Pd", atomicNo: 46, color: "#CFC3E5", atomicMass: 106.42, name: "Palladium" },
    { symbol: "Ag", atomicNo: 47, color: "#CFC3E5", atomicMass: 107.87, name: "Silver" },
    { symbol: "Cd", atomicNo: 48, color: "#CFC3E5", atomicMass: 112.41, name: "Cadmium" },
    { symbol: "In", atomicNo: 49, color: "#F9CDD2", atomicMass: 114.82, name: "Indium" },
    { symbol: "Sn", atomicNo: 50, color: "#F9CDD2", atomicMass: 118.71, name: "Tin" },
    { symbol: "Sb", atomicNo: 51, color: "#FEF188", atomicMass: 121.76, name: "Antimony" },
    { symbol: "Te", atomicNo: 52, color: "#FEF188", atomicMass: 127.6, name: "Tellurium" },
    { symbol: "I", atomicNo: 53, color: "#AFD5AA", atomicMass: 126.9, name: "Iodine" },
    { symbol: "Xe", atomicNo: 54, color: "#EEEEEE", atomicMass: 131.29, name: "Xenon" }
  ],
  [
    { symbol: "Cs", atomicNo: 55, color: "#FAE1B8", atomicMass: 132.91, name: "Caesium" },
    { symbol: "Ba", atomicNo: 56, color: "#F6CD8B", atomicMass: 137.33, name: "Barium" },
    { symbol: "La", atomicNo: 57, color: "#E6EEA6", atomicMass: 138.91, name: "Lanthanum" },
    { symbol: "Hf", atomicNo: 72, color: "#CFC3E5", atomicMass: 178.49, name: "Hafnium" },
    { symbol: "Ta", atomicNo: 73, color: "#CFC3E5", atomicMass: 180.95, name: "Tantalum" },
    { symbol: "W", atomicNo: 74, color: "#CFC3E5", atomicMass: 183.84, name: "Tungsten" },
    { symbol: "Re", atomicNo: 75, color: "#CFC3E5", atomicMass: 186.21, name: "Rhenium" },
    { symbol: "Os", atomicNo: 76, color: "#CFC3E5", atomicMass: 190.23, name: "Osmium" },
    { symbol: "Ir", atomicNo: 77, color: "#CFC3E5", atomicMass: 192.22, name: "Iridium" },
    { symbol: "Pt", atomicNo: 78, color: "#CFC3E5", atomicMass: 195.08, name: "Platinum" },
    { symbol: "Au", atomicNo: 79, color: "#CFC3E5", atomicMass: 196.97, name: "Gold" },
    { symbol: "Hg", atomicNo: 80, color: "#CFC3E5", atomicMass: 200.59, name: "Mercury" },
    { symbol: "Tl", atomicNo: 81, color: "#F9CDD2", atomicMass: 204.38, name: "Thallium" },
    { symbol: "Pb", atomicNo: 82, color: "#F9CDD2", atomicMass: 207.2, name: "Lead" },
    { symbol: "Bi", atomicNo: 83, color: "#FEF188", atomicMass: 208.98, name: "Bismuth" },
    { symbol: "Po", atomicNo: 84, color: "#FEF188", atomicMass: 209, name: "Polonium" },
    { symbol: "At", atomicNo: 85, color: "#AFD5AA", atomicMass: 210, name: "Astatine" },
    { symbol: "Rn", atomicNo: 86, color: "#EEEEEE", atomicMass: 222, name: "Radon" }
  ],
  [
    { symbol: "Fr ", atomicNo: 87, color: "#FAE1B8", atomicMass: 223, name: "Francium" },
    { symbol: "Ra", atomicNo: 88, color: "#F6CD8B", atomicMass: 226, name: "Radium" },
    { symbol: "Ac", atomicNo: 89, color: "#BDE4F9", atomicMass: 227, name: "Actinium" },
    { symbol: "Rf", atomicNo: 104, color: "#CFC3E5", atomicMass: 261, name: "Rutherfordium" },
    { symbol: "Db", atomicNo: 105, color: "#CFC3E5", atomicMass: 262, name: "Dubnium" },
    { symbol: "Sg", atomicNo: 106, color: "#CFC3E5", atomicMass: 266, name: "Seaborgium" },
    { symbol: "Bh", atomicNo: 107, color: "#CFC3E5", atomicMass: 264, name: "Bohrium" },
    { symbol: "Hs", atomicNo: 108, color: "#CFC3E5", atomicMass: 269, name: "Hassium" },
    { symbol: "Mt", atomicNo: 109, color: "#CFC3E5", atomicMass: 268, name: "Meitnerium" },
    { symbol: "Ds", atomicNo: 110, color: "#CFC3E5", atomicMass: 271, name: "Darmstadtium" },
    { symbol: "Rg", atomicNo: 111, color: "#CFC3E5", atomicMass: 272, name: "Roentgenium" },
    { symbol: "Cn", atomicNo: 112, color: "#CFC3E5", atomicMass: 285, name: "Copernicium" },
    { symbol: "Nh", atomicNo: 113, color: "#F9CDD2", atomicMass: 286, name: "Nihonium" },
    { symbol: "Fl", atomicNo: 114, color: "#F9CDD2", atomicMass: 289, name: "Flerovium" },
    { symbol: "Mc", atomicNo: 115, color: "#F9CDD2", atomicMass: 288, name: "Moscovium" },
    { symbol: "Lv", atomicNo: 116, color: "#F9CDD2", atomicMass: 293, name: "Livermorium" },
    { symbol: "Ts", atomicNo: 117, color: "#AFD5AA", atomicMass: 294, name: "Tennessine" },
    { symbol: "Og", atomicNo: 118, color: "#EEEEEE", atomicMass: 294, name: "Oganesson" }
  ]
];

const fBlockElements = [
  { symbol: "La", atomicNo: 57, color: "#E6EEA6", atomicMass: 138.90547, name: "Lanthanum" },

  { symbol: "Ce", atomicNo: 58, color: "#E6EEA6", atomicMass: 140.116, name: "Cerium" },
  { symbol: "Pr", atomicNo: 59, color: "#E6EEA6", atomicMass: 140.90765, name: "Praseodymium" },
  { symbol: "Nd", atomicNo: 60, color: "#E6EEA6", atomicMass: 144.24, name: "Neodymium" },
  { symbol: "Pm", atomicNo: 61, color: "#E6EEA6", atomicMass: 146.9151, name: "Promethium" },
  { symbol: "Sm", atomicNo: 62, color: "#E6EEA6", atomicMass: 150.36, name: "Samarium" },
  { symbol: "Eu", atomicNo: 63, color: "#E6EEA6", atomicMass: 151.964, name: "Europium" },
  { symbol: "Gd", atomicNo: 64, color: "#E6EEA6", atomicMass: 157.25, name: "Gadolinium" },
  { symbol: "Tb", atomicNo: 65, color: "#E6EEA6", atomicMass: 158.92535, name: "Terbium" },
  { symbol: "Dy", atomicNo: 66, color: "#E6EEA6", atomicMass: 162.5, name: "Dysprosium" },
  { symbol: "Ho", atomicNo: 67, color: "#E6EEA6", atomicMass: 164.93032, name: "Holmium" },
  { symbol: "Er", atomicNo: 68, color: "#E6EEA6", atomicMass: 167.259, name: "Erbium" },
  { symbol: "Tm", atomicNo: 69, color: "#E6EEA6", atomicMass: 168.93422, name: "Thulium" },
  { symbol: "Yb", atomicNo: 70, color: "#E6EEA6", atomicMass: 173.04, name: "Ytterbium" },
  { symbol: "Lu", atomicNo: 71, color: "#E6EEA6", atomicMass: 174.967, name: "Lutetium" },
];

const actinideElements = [
  { symbol: "Ac", atomicNo: 89, color: "#BDE4F9", atomicMass: 227, name: "Actinium" },
  { symbol: "Th", atomicNo: 90, color: "#BDE4F9", atomicMass: 232, name: "Thorium" },
  { symbol: "Pa", atomicNo: 91, color: "#BDE4F9", atomicMass: 231, name: "Protactinium" },
  { symbol: "U", atomicNo: 92, color: "#BDE4F9", atomicMass: 238, name: "Uranium" },
  { symbol: "Np", atomicNo: 93, color: "#BDE4F9", atomicMass: 237, name: "Neptunium" },
  { symbol: "Pu", atomicNo: 94, color: "#BDE4F9", atomicMass: 244, name: "Plutonium" },
  { symbol: "Am", atomicNo: 95, color: "#BDE4F9", atomicMass: 243, name: "Americium" },
  { symbol: "Cm", atomicNo: 96, color: "#BDE4F9", atomicMass: 247, name: "Curium" },
  { symbol: "Bk", atomicNo: 97, color: "#BDE4F9", atomicMass: 247, name: "Berkelium" },
  { symbol: "Cf", atomicNo: 98, color: "#BDE4F9", atomicMass: 251, name: "Curium" },
  { symbol: "Es", atomicNo: 99, color: "#BDE4F9", atomicMass: 252, name: "Einsteinium" },
  { symbol: "Fm", atomicNo: 100, color: "#BDE4F9", atomicMass: 257, name: "Fermium" },
  { symbol: "Md", atomicNo: 101, color: "#BDE4F9", atomicMass: 258, name: "Mendelevium" },
  { symbol: "No", atomicNo: 102, color: "#BDE4F9", atomicMass: 259, name: "Nobelium" },
  { symbol: "Lr", atomicNo: 103, color: "#BDE4F9", atomicMass: 262, name: "Lawrencium" },
];

const fBlock = [
  { label: "Lanthanides", elements: fBlockElements },
  { label: "Actinides", elements: actinideElements }
];